openapi: 3.1.3
info:
  title: EVM Transaction Indexer API
  version: 1.0.0
  contact: {}
servers:
  - url: http://127.0.0.1:3001
    description: Local server
    variables: {}
paths:
  /current_block:
    get:
      summary: Get current indexed block
      description: Get current indexed block
      operationId: getCurrentIndexedBlock
      responses:
        "200":
          description: get current indexed block
          headers:
            Content-Location:
              schema:
                type: string
                example: /current_block
            Content-Range:
              schema:
                type: string
                example: 0-0/*
            Date:
              schema:
                type: string
                example: Fri, 23 Jun 2023 02:00:14 GMT
            Server:
              schema:
                type: string
                example: postgrest/11.1.0 (1f13e43)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    max:
                      type: number
                      example: 17539093
                example:
                  - max: 17539093
              examples:
                get current indexed block:
                  value:
                    - max: 17539093
  /events:
    get:
      summary: Get list of events with pagination
      description: Get list of events with pagination
      operationId: getListOfEventsWithPagination
      parameters:
        - name: limit
          in: query
          schema:
            type: string
            example: "2"
          description: item per page
        - name: offset
          in: query
          schema:
            type: string
            example: "0"
          description: skipped item 0=first page, then offset=limit*page
        - name: order
          in: query
          schema:
            type: string
            example: time.desc
        - name: time
          in: query
          schema:
            type: string
            example: lte.1687399187
        - name: tx_hash
          in: query
          schema:
            type: string
            example: >-
              imatch.0x5aee9b24acb0b7ae1d87bee2be24dfd9d0533d388f879e9f5683e5ba48ce1d30
        - name: Prefer
          in: header
          schema:
            type: string
            example: count=exact
      responses:
        "200":
          description: get events by tx hash within time range
          headers:
            Content-Location:
              schema:
                type: string
                example: >-
                  /events?limit=2&offset=0&order=time.desc&time=lte.1687399187,gte.1687399187&tx_hash=imatch.0x5aee9b24acb0b7ae1d87bee2be24dfd9d0533d388f879e9f5683e5ba48ce1d30
            Content-Range:
              schema:
                type: string
                example: 0-0/1
            Date:
              schema:
                type: string
                example: Thu, 22 Jun 2023 19:37:11 GMT
            Server:
              schema:
                type: string
                example: postgrest/11.1.0 (1f13e43)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    block:
                      type: number
                      example: 17532055
                    contract_to:
                      type: string
                      example: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                    gas:
                      type: number
                      example: 123561
                    gas_price:
                      type: number
                      example: 81774747180
                    symbols:
                      type: string
                      example: WETH_USDC
                    time:
                      type: number
                      example: 1687399187
                    total_fee:
                      nullable: true
                      example: null
                    tx_from:
                      type: string
                      example: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                    tx_hash:
                      type: string
                      example: >-
                        0x5aee9b24acb0b7ae1d87bee2be24dfd9d0533d388f879e9f5683e5ba48ce1d30
                    tx_to:
                      type: string
                      example: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                    value:
                      nullable: true
                      example: null
                example:
                  - block: 17532055
                    contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                    gas: 123561
                    gas_price: 81774747180
                    symbols: WETH_USDC
                    time: 1687399187
                    total_fee: null
                    tx_from: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                    tx_hash: >-
                      0x5aee9b24acb0b7ae1d87bee2be24dfd9d0533d388f879e9f5683e5ba48ce1d30
                    tx_to: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                    value: null
              examples:
                get events by tx hash within time range:
                  value:
                    - block: 17532055
                      contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                      gas: 123561
                      gas_price: 81774747180
                      symbols: WETH_USDC
                      time: 1687399187
                      total_fee: null
                      tx_from: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                      tx_hash: >-
                        0x5aee9b24acb0b7ae1d87bee2be24dfd9d0533d388f879e9f5683e5ba48ce1d30
                      tx_to: "0x9507c04b10486547584c37bcbd931b2a4fee9a41"
                      value: null
        "206":
          description: get event by time range
          headers:
            Content-Location:
              schema:
                type: string
                example: >-
                  /events?limit=2&offset=0&order=time.desc&time=lte.1686589199,gte.1686502800
            Content-Range:
              schema:
                type: string
                example: 0-1/246
            Date:
              schema:
                type: string
                example: Thu, 22 Jun 2023 19:36:09 GMT
            Server:
              schema:
                type: string
                example: postgrest/11.1.0 (1f13e43)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    block:
                      type: number
                      example: 17465240
                    contract_to:
                      type: string
                      example: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                    gas:
                      type: number
                      example: 178587
                    gas_price:
                      type: number
                      example: 17593591580
                    symbols:
                      type: string
                      example: WETH_USDC
                    time:
                      type: number
                      example: 1686588347
                    total_fee:
                      nullable: true
                      example: null
                    tx_from:
                      type: string
                      example: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                    tx_hash:
                      type: string
                      example: >-
                        0xb1cec08ef900fd774c755059185f44028ae2f5feaaaf3d8a9f125efe211143a9
                    tx_to:
                      type: string
                      example: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                    value:
                      nullable: true
                      example: null
                example:
                  - block: 17465240
                    contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                    gas: 178587
                    gas_price: 17593591580
                    symbols: WETH_USDC
                    time: 1686588347
                    total_fee: null
                    tx_from: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                    tx_hash: >-
                      0xb1cec08ef900fd774c755059185f44028ae2f5feaaaf3d8a9f125efe211143a9
                    tx_to: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                    value: null
                  - block: 17465227
                    contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                    gas: 653284
                    gas_price: 19607209391
                    symbols: WETH_USDC
                    time: 1686588167
                    total_fee: null
                    tx_from: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
                    tx_hash: >-
                      0x672fc3d7112fa8790d51c864a944fb3d4f79a0dde6ede6811c49f9a4e282bad7
                    tx_to: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
                    value: null
              examples:
                get event by time range:
                  value:
                    - block: 17465240
                      contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                      gas: 178587
                      gas_price: 17593591580
                      symbols: WETH_USDC
                      time: 1686588347
                      total_fee: null
                      tx_from: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                      tx_hash: >-
                        0xb1cec08ef900fd774c755059185f44028ae2f5feaaaf3d8a9f125efe211143a9
                      tx_to: "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad"
                      value: null
                    - block: 17465227
                      contract_to: "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
                      gas: 653284
                      gas_price: 19607209391
                      symbols: WETH_USDC
                      time: 1686588167
                      total_fee: null
                      tx_from: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
                      tx_hash: >-
                        0x672fc3d7112fa8790d51c864a944fb3d4f79a0dde6ede6811c49f9a4e282bad7
                      tx_to: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
                      value: null
tags: []
